from __future__ import annotations

from typing import Any, Literal

import torch
from torch import Tensor

from atc_starrygl_lib.lib import is_bts_sampler_available, load_bts_sampler_module

DIST_FORMAT = "atc_dist_v1"
PartitionAlgorithm = Literal["metis", "speed_partition", "chunk_load_balance"]


def build_dist_plan(
    *,
    src: Tensor,
    dst: Tensor,
    ts: Tensor | None,
    num_nodes: int,
    world_size: int,
    time_ptr_2: Tensor,
    algorithm: str,
    chunks_per_rank: int,
    hot_ratio: float = 0.0,
    hot_topk: int = 0,
    node_count_weight: float = 1.0,
    speed_beta: float = 0.5,
    speed_topk_type: str = "degree",
) -> dict[str, Any]:
    """Build the shared global partition plan for CTDG and DTDG.

    This module deliberately does not encode ``master_dist_index`` because the
    packed local row depends on the per-rank layout generated by ``rank.py``.
    """

    src = src.long().cpu().contiguous()
    dst = dst.long().cpu().contiguous()
    ts_cpu = None if ts is None else ts.cpu().contiguous()
    time_ptr_2 = time_ptr_2.long().cpu().contiguous()
    num_nodes = int(num_nodes)
    world_size = int(world_size)
    chunks_per_rank = int(chunks_per_rank)
    num_edges = int(src.numel())
    speed_layout: dict[str, Any] = {}
    if algorithm == "speed_partition":
        speed = run_speed_partition(
            src=src,
            dst=dst,
            ts=ts_cpu,
            num_nodes=num_nodes,
            world_size=world_size,
            beta=float(speed_beta),
            topk_ratio=float(hot_ratio),
            topk_type=str(speed_topk_type),
        )
        node_owner = speed["node_owner"].long()
        edge_owner = speed["edge_owner"].long()
        replica_mask = speed["replica_mask"].bool()
        hot_node_ids = speed["hot_node_ids"].long()
        node_master = speed["node_master"].long()
        speed_layout = {key: value for key, value in speed.items() if key.endswith("_by_part")}
        node_to_chunk, chunk_ptr, chunk_nodes, chunk_owner = build_local_metis_chunks(
            src=src,
            dst=dst,
            node_owner=node_owner,
            chunks_per_rank=chunks_per_rank,
            world_size=world_size,
        )
    elif algorithm == "metis":
        node_owner = run_metis_partition(src=src, dst=dst, num_nodes=num_nodes, world_size=world_size)
        replica_mask, hot_node_ids, node_master = normalize_replica(
            src=src,
            dst=dst,
            node_owner=node_owner,
            hot_ratio=float(hot_ratio),
            hot_topk=int(hot_topk),
        )
        edge_owner = node_owner.index_select(0, dst)
        node_to_chunk, chunk_ptr, chunk_nodes, chunk_owner = build_local_metis_chunks(
            src=src,
            dst=dst,
            node_owner=node_owner,
            chunks_per_rank=chunks_per_rank,
            world_size=world_size,
        )
    elif algorithm == "chunk_load_balance":
        num_chunks = world_size * chunks_per_rank
        node_to_chunk = build_global_metis_chunks(src=src, dst=dst, num_nodes=num_nodes, num_chunks=num_chunks)
        chunk_ptr, chunk_nodes = build_chunk_csr(node_to_chunk=node_to_chunk, num_chunks=num_chunks)
        chunk_load = compute_chunk_load(
            src=src,
            dst=dst,
            node_to_chunk=node_to_chunk,
            time_ptr_2=time_ptr_2,
            num_chunks=num_chunks,
            node_count_weight=float(node_count_weight),
        )
        chunk_owner = assign_chunks_by_load(chunk_load, world_size=world_size)
        node_owner = chunk_owner.index_select(0, node_to_chunk)
        replica_mask, hot_node_ids, node_master = normalize_replica(
            src=src,
            dst=dst,
            node_owner=node_owner,
            hot_ratio=float(hot_ratio),
            hot_topk=int(hot_topk),
        )
        edge_owner = chunk_owner.index_select(0, node_to_chunk.index_select(0, dst))
    else:
        raise ValueError(f"unsupported partition algorithm: {algorithm}")

    if algorithm != "chunk_load_balance":
        chunk_load = compute_chunk_load(
            src=src,
            dst=dst,
            node_to_chunk=node_to_chunk,
            time_ptr_2=time_ptr_2,
            num_chunks=int(chunk_owner.numel()),
            node_count_weight=float(node_count_weight),
        )

    return {
        "format": DIST_FORMAT,
        "world_size": world_size,
        "num_nodes": num_nodes,
        "num_edges": num_edges,
        "node_to_chunk": node_to_chunk.long().contiguous(),
        "chunk_ptr": chunk_ptr.long().contiguous(),
        "chunk_nodes": chunk_nodes.long().contiguous(),
        "chunk_owner": chunk_owner.long().contiguous(),
        "node_owner": node_owner.long().contiguous(),
        "edge_owner": edge_owner.long().contiguous(),
        "replica_mask": replica_mask.bool().contiguous(),
        "replica_nodes": replica_mask.nonzero(as_tuple=True)[0].long().contiguous(),
        "hot_node_ids": hot_node_ids.long().contiguous(),
        "node_master": node_master.long().contiguous(),
        "master_dist_index": None,
        "edge_dist_index": None,
        "chunk_load": chunk_load.float().contiguous(),
        "chunk_load_mean": chunk_load.mean(dim=0).float().contiguous(),
        "chunk_load_std": chunk_load.std(dim=0, unbiased=False).float().contiguous(),
        "partition_algorithm": str(algorithm),
        "chunks_per_rank": chunks_per_rank,
    } | speed_layout


def build_local_metis_chunks(
    *,
    src: Tensor,
    dst: Tensor,
    node_owner: Tensor,
    chunks_per_rank: int,
    world_size: int,
) -> tuple[Tensor, Tensor, Tensor, Tensor]:
    src = src.long().cpu().contiguous()
    dst = dst.long().cpu().contiguous()
    node_owner = node_owner.long().cpu().contiguous()
    chunks_per_rank = int(chunks_per_rank)
    world_size = int(world_size)
    num_nodes = int(node_owner.numel())
    num_chunks = world_size * chunks_per_rank
    node_to_chunk = torch.empty(num_nodes, dtype=torch.long)
    for rank in range(world_size):
        nodes = (node_owner == rank).nonzero(as_tuple=True)[0]
        if nodes.numel() == 0:
            continue
        local_chunk = _metis_partition_subset(
            src=src,
            dst=dst,
            nodes=nodes,
            num_nodes=num_nodes,
            num_parts=chunks_per_rank,
        )
        node_to_chunk[nodes] = rank * chunks_per_rank + local_chunk
    chunk_ptr, chunk_nodes = build_chunk_csr(node_to_chunk=node_to_chunk, num_chunks=num_chunks)
    chunk_owner = torch.arange(num_chunks, dtype=torch.long) // chunks_per_rank
    return node_to_chunk, chunk_ptr, chunk_nodes, chunk_owner


def build_global_metis_chunks(*, src: Tensor, dst: Tensor, num_nodes: int, num_chunks: int) -> Tensor:
    return run_metis_partition(src=src, dst=dst, num_nodes=int(num_nodes), world_size=int(num_chunks))


def build_chunk_csr(*, node_to_chunk: Tensor, num_chunks: int) -> tuple[Tensor, Tensor]:
    node_to_chunk = node_to_chunk.long().cpu().contiguous()
    order = torch.argsort(node_to_chunk, stable=True)
    counts = torch.bincount(node_to_chunk, minlength=int(num_chunks))
    chunk_ptr = torch.zeros(int(num_chunks) + 1, dtype=torch.long)
    chunk_ptr[1:] = counts.cumsum(0)
    return chunk_ptr, order.long().contiguous()


def compute_chunk_load(
    *,
    src: Tensor,
    dst: Tensor,
    node_to_chunk: Tensor,
    time_ptr_2: Tensor,
    num_chunks: int,
    node_count_weight: float = 1.0,
) -> Tensor:
    src = src.long().cpu()
    dst = dst.long().cpu()
    node_to_chunk = node_to_chunk.long().cpu()
    time_ptr_2 = time_ptr_2.long().cpu()
    load = torch.zeros(int(time_ptr_2.size(0)), int(num_chunks), dtype=torch.float32)
    num_nodes = int(node_to_chunk.numel())
    stride = num_nodes + 1
    for t in range(int(time_ptr_2.size(0))):
        begin = int(time_ptr_2[t, 0])
        end = int(time_ptr_2[t, 1])
        if end <= begin:
            continue
        s = src[begin:end]
        d = dst[begin:end]
        chunks = node_to_chunk.index_select(0, d)
        event_count = torch.bincount(chunks, minlength=int(num_chunks)).float()
        pair_src = chunks * stride + s
        pair_dst = chunks * stride + d
        unique_pairs = torch.unique(torch.cat([pair_src, pair_dst], dim=0))
        unique_chunks = (unique_pairs // stride).long()
        node_count = torch.bincount(unique_chunks, minlength=int(num_chunks)).float()
        load[t] = event_count + float(node_count_weight) * node_count
    return load


def assign_chunks_by_load(chunk_load: Tensor, *, world_size: int) -> Tensor:
    chunk_load = chunk_load.float().cpu()
    mean = chunk_load.mean(dim=0)
    std = chunk_load.std(dim=0, unbiased=False)
    order = torch.argsort(mean + std, descending=True, stable=True)
    owner = torch.empty(int(chunk_load.size(1)), dtype=torch.long)
    for idx, cid in enumerate(order.tolist()):
        owner[int(cid)] = int(idx % int(world_size))
    return owner


def normalize_replica(
    *,
    src: Tensor,
    dst: Tensor,
    node_owner: Tensor,
    hot_ratio: float = 0.0,
    hot_topk: int = 0,
    replica_mask: Tensor | None = None,
    hot_node_ids: Tensor | None = None,
    node_master: Tensor | None = None,
) -> tuple[Tensor, Tensor, Tensor]:
    node_owner = node_owner.long().cpu().contiguous()
    num_nodes = int(node_owner.numel())
    if replica_mask is None:
        replica_mask = torch.zeros(num_nodes, dtype=torch.bool)
    else:
        replica_mask = replica_mask.bool().cpu().clone()
    if hot_node_ids is None:
        hot_node_ids = _hot_nodes_by_degree(src, dst, num_nodes=num_nodes, hot_ratio=hot_ratio, hot_topk=hot_topk)
    else:
        hot_node_ids = hot_node_ids.long().cpu().contiguous()
    if hot_node_ids.numel() > 0:
        replica_mask[hot_node_ids] = True
    if node_master is None:
        node_master = node_owner.clone()
    else:
        node_master = node_master.long().cpu().clone()
        missing = node_master < 0
        node_master[missing] = node_owner[missing]
    node_master[~replica_mask] = node_owner[~replica_mask]
    return replica_mask, hot_node_ids, node_master


def run_speed_partition(
    *,
    src: Tensor,
    dst: Tensor,
    ts: Tensor | None,
    num_nodes: int,
    world_size: int,
    beta: float,
    topk_ratio: float,
    topk_type: str,
) -> dict[str, Tensor]:
    if not is_bts_sampler_available():
        raise RuntimeError("speed_partition requires libstarrygl_sampler")
    mod = load_bts_sampler_module()
    ts_arg = torch.arange(src.numel(), dtype=torch.float64) if ts is None else ts.to(torch.float64)
    out = mod.speed_partition(
        src.long().contiguous(),
        dst.long().contiguous(),
        ts_arg.contiguous(),
        int(num_nodes),
        int(world_size),
        float(beta),
        float(topk_ratio),
        str(topk_type),
    )
    node_owner = out.get("node_parts", out.get("node_master")).long().cpu()
    edge_owner = out.get("edge_parts", out.get("edge_owner")).long().cpu()
    replica_mask, hot_node_ids, node_master = normalize_replica(
        src=src,
        dst=dst,
        node_owner=node_owner,
        replica_mask=out.get("replica_mask"),
        hot_node_ids=out.get("hot_node_ids"),
        node_master=out.get("node_master", node_owner),
    )
    result = {
        "node_owner": node_owner,
        "edge_owner": edge_owner,
        "replica_mask": replica_mask,
        "hot_node_ids": hot_node_ids,
        "node_master": node_master,
    }
    for key in (
        "local_node_ids_by_part",
        "owned_node_ids_by_part",
        "replica_node_ids_by_part",
        "shadow_node_ids_by_part",
        "edge_ids_by_part",
    ):
        if key in out:
            result[key] = out[key]
    return result


def run_metis_partition(*, src: Tensor, dst: Tensor, num_nodes: int, world_size: int) -> Tensor:
    if int(world_size) <= 1:
        return torch.zeros(int(num_nodes), dtype=torch.long)
    try:
        import dgl
    except Exception as exc:
        raise RuntimeError("metis partition requires dgl") from exc
    graph = dgl.graph((src.cpu(), dst.cpu()), num_nodes=int(num_nodes))
    graph = dgl.to_bidirected(graph, copy_ndata=False)
    part = dgl.metis_partition_assignment(graph, int(world_size))
    return part.long().cpu().contiguous()


def _metis_partition_subset(
    *,
    src: Tensor,
    dst: Tensor,
    nodes: Tensor,
    num_nodes: int,
    num_parts: int,
) -> Tensor:
    nodes = nodes.long().cpu().contiguous()
    num_parts = int(num_parts)
    if num_parts <= 1:
        return torch.zeros(int(nodes.numel()), dtype=torch.long)
    if int(nodes.numel()) < num_parts:
        return torch.arange(int(nodes.numel()), dtype=torch.long) % num_parts
    local = torch.full((int(num_nodes),), -1, dtype=torch.long)
    local[nodes] = torch.arange(int(nodes.numel()), dtype=torch.long)
    keep = (local.index_select(0, src.long()) >= 0) & (local.index_select(0, dst.long()) >= 0)
    if not bool(keep.any()):
        return torch.arange(int(nodes.numel()), dtype=torch.long) % num_parts
    local_src = local.index_select(0, src[keep].long())
    local_dst = local.index_select(0, dst[keep].long())
    return run_metis_partition(src=local_src, dst=local_dst, num_nodes=int(nodes.numel()), world_size=num_parts)


def _hot_nodes_by_degree(src: Tensor, dst: Tensor, *, num_nodes: int, hot_ratio: float, hot_topk: int) -> Tensor:
    k = int(hot_topk)
    if k <= 0 and hot_ratio > 0.0:
        k = int(round(float(hot_ratio) * int(num_nodes)))
    k = max(0, min(k, int(num_nodes)))
    if k == 0:
        return torch.empty(0, dtype=torch.long)
    deg = torch.zeros(int(num_nodes), dtype=torch.long)
    one = torch.ones(int(src.numel()), dtype=torch.long)
    deg.scatter_add_(0, src.long(), one)
    deg.scatter_add_(0, dst.long(), one)
    hot = torch.topk(deg, k=k, largest=True, sorted=False).indices
    return hot[deg[hot] > 0].long().cpu().contiguous()
